# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_in',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answervote',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='answervote',
            name='updated_in',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_in',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='updated_in',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='updated_in',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
