# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_created', to='app.UserExtension'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_updated', to='app.UserExtension'),
        ),
        migrations.AlterField(
            model_name='question',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_created', to='app.UserExtension'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_updated', to='app.UserExtension'),
        ),
    ]
