# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(to='app.Question'),
        ),
    ]
