# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercomment',
            name='app_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.UserExtension'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='app_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.UserExtension'),
            preserve_default=False,
        ),
    ]
